#!/usr/bin/env bash
# Check if all required parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

SCP_COMMAND="scp -o StrictHostKeyChecking=no -i $SSH_KEY_PATH $FILE_PATH $USERNAME@$SERVER_IP:~/"

$SCP_COMMAND

if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "Error transferring file."
fi

