#!/usr/bin/env bash
# Update package list and install Nginx
apt-get update
apt-get install -y nginx

sed -i 's/80 default_server/80 default_server;/g' /etc/nginx/sites-available/default

kill -HUP $(pgrep nginx)

echo "Hello World!" > /var/www/html/index.html
