#!/usr/bin/env bash
# Install Nginx
sudo apt update
sudo apt install -y nginx

# Create directory for HTML files
sudo mkdir -p /var/www/html

# Create a Hello World HTML file
echo "<html><head><title>Hello World!</title></head><body><p>Hello World!</p></body></html>" | /var/www/html/index.html

# Configure Nginx
sudo bash -c 'cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL'

# Restart Nginx
sudo service nginx restart


