#!/usr/bin/env bash
# Update the package index
apt-get update -y
apt-get install -y nginx

server_block="/etc/nginx/sites-available/default"
sed -i '/^\s*location \/ {/a \ \n \ \ \ \ location \/redirect_me {\n \ \ \ \ \ \ \ return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n \ \ \ \ }\n' "$server_block"

kill -HUP "$(pgrep nginx)"
