#!/usr/bin/env bash
# Update package list and install <link>nginx</link>
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    location = /redirect_me {
        return 301 <link>https://www.example.com/</link>;
    }
}
EOL

sudo service nginx restart
curl localhost
