#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set the custom HTTP response header
echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/conf.d/custom_response_headers.conf

# Restart Nginx to apply the changes
sudo systemctl restart nginx
