#!/usr/bin/env bash
# Update package list and install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy to send traffic to web-01 and web-02 using roundrobin algorithm
echo "
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 54.242.190.120 54.242.190.120:80 check
    server 54.237.115.5   54.237.115.5:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Enable HAProxy init script for management
sudo systemctl enable haproxy

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy
