#!/usr/bin/env bash

# Install HAproxy
sudo apt update
sudo apt install haproxy -y

# Configure HAproxy to send traffic to web-01 and web-02
echo "
frontend app
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy service to apply changes
sudo service haproxy restart
