#!/usr/bin/env bash
#this script shows it own pid

trap graceful_shutdown SIGINT 
trap close SIGQUIT 
trap excute SIGTERM

echo $$ > /var/run/myscript.pid

graceful_shutdown()
{
	  echo "Y U no love me?!"
	  exit
}

close()
{
	 rm /var/run/myscript.pid
	 kill  SIGTERM $$
	 exit
}

excute()
{
	echo "I hate the kill command"
	kill  SIGTERM $$
	exit
}
while true
do 
	echo "To infinity and beyond"
done
