#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.

count=0

while [ $count -lt 10 ]
do
  echo "Best School"
  if [ $count -eq 8 ]
  then
	  echo "Hi"
  fi
  (( count++ ))
done
