#!/usr/bin/env bash
#edit the host files 
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" >> ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
cp -f ~/hosts.new /etc/hosts
