#!/usr/bin/env bash
# Stop the Nginx service
systemctl stop nginx

# Edit the Nginx configuration to run as the nginx user and listen on all active IPs on port 8080
sed -i 's/user  nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen       80;/listen       8080;/' /etc/nginx/nginx.conf

# Start the Nginx service
systemctl start nginx
